### ISSUE TITLE
执行指令出错

### ISSUE THREAD

**Issue by Cl-arctos** [iiiusky/alicloud-tools#2]
显示目标操做系统是windows,但是在值行执行令时却使用linux的那个值行，设置-t runbat和powershell 最后也显示的时使用sellscript执行

**Comment by iiiusky** [comment]
有截图吗？



---原始邮件---
发件人: "Cl-arctos"<notifications@github.com&gt;
发送时间: 2020年11月3日(周二) 下午2:28
收件人: "iiiusky/alicloud-tools"<alicloud-tools@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [iiiusky/alicloud-tools] 执行指令出错 (#2)




 
显示目标操做系统是windows,但是在值行执行令时却使用linux的那个值行，设置-t runbat和powershell 最后也显示的时使用sellscript执行

**Comment by Q1ngShan** [comment]
![image](https://user-images.githubusercontent.com/24487351/98506230-fcb31b80-2295-11eb-8358-0fcbd9ab373a.png)
